### ISSUE TITLE
rest-server 0.11.0 fails with usernames with underscores

### ISSUE THREAD

**Issue by eliba** [FIFTY2Technology/ansible-role-restic_server#1]
unfortunately, in the current version of `rest-server`, the REST authentication is broken with usernames containing underscores. This role uses underscores in usernames, since hostnames of backup clients are used as usernames, and dots are converted into underscores.

This is a known problem and got fixed already :tada:, see [rest-server #182](https://github.com/restic/rest-server/issues/182).

You can work around this issue with the `restic_server_binary_install_dir` variable and building `rest-server` from the current `master` branch, e.g.:
```
$ git clone https://github.com/restic/rest-server.git
$ cd rest-server
$ docker run -ti -v $(pwd):/src:Z docker.io/library/golang:latest /bin/bash
  # cd /src
  # go build ./cmd/rest-server/
$ ls -la rest-server
-rwxr-xr-x. 1 1000 1000 13994196 Aug 31 15:45 rest-server
```
Copy the `rest-server` binary into the directory you set as `restic_server_binary_install_dir` (e.g. into `/tmp`) and deploy the role, e.g.:
```
- hosts: backupservers
  gather_facts: true

  vars:
    restic_server_binary_install_dir: /tmp

  roles:
  - role: restic_server
```
